version: "3.4"

services:
  interval:
    build:
      context: .
    depends_on:
      - caluma

  db:
    image: postgres:9.6-alpine@sha256:a7fe157e12a492fae58d10fe102c437b9e71ae911592a5ca4022181b921f0262
    environment:
      - POSTGRES_USER=caluma
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -p ${DATABASE_PORT:-5432}

  caluma:
    image: projectcaluma/caluma:latest@sha256:cb8ccf282cb6b6525ffeaa3997b956685a96a88c60fa1fe3ba2b5092bdcc7bcc
    ports:
      - "8000:8000"
    depends_on:
      - db

    environment:
      - DATABASE_HOST=db
      - SECRET_KEY=uuuuuu
      - ALLOWED_HOSTS=*
      - DATABASE_PASSWORD=caluma
      - VISIBILITY_CLASSES=caluma.core.visibilities.Any
      - PERMISSION_CLASSES=caluma.core.permissions.AllowAny

volumes:
  dbdata:
