version: "3.4"

services:
  interval:
    build:
      context: .
    depends_on:
      - caluma

  db:
    image: postgres:9.6-alpine@sha256:2a3cfc86ef3fcd63b131cf15b04b031f7d5a167684d700dd98d9a78a9c6415a0
    environment:
      - POSTGRES_USER=caluma
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -p ${DATABASE_PORT:-5432}

  caluma:
    image: projectcaluma/caluma:latest@sha256:3450a17a28291e64807afb9f37de3ae519aad6b9dfb3e12bc21f76a46b310e8c
    ports:
      - "8000:8000"
    depends_on:
      - db

    environment:
      - DATABASE_HOST=db
      - SECRET_KEY=uuuuuu
      - ALLOWED_HOSTS=*
      - DATABASE_PASSWORD=caluma
      - VISIBILITY_CLASSES=caluma.core.visibilities.Any
      - PERMISSION_CLASSES=caluma.core.permissions.AllowAny

volumes:
  dbdata:
