version: "3.4"

services:
  interval:
    build:
      context: .
    depends_on:
      - caluma

  db:
    image: postgres:9.6-alpine@sha256:de3efddbc71dbdbf236fae5abda26cbac68204cb2410be5be3a12bfe2da9a871
    environment:
      - POSTGRES_USER=caluma
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -p ${DATABASE_PORT:-5432}

  caluma:
    image: projectcaluma/caluma:latest@sha256:ec73722c9d40e3786309de7d3885bef80558932bbfdf0b34701b11d997241e8a
    ports:
      - "8000:8000"
    depends_on:
      - db

    environment:
      - DATABASE_HOST=db
      - SECRET_KEY=uuuuuu
      - ALLOWED_HOSTS=*
      - DATABASE_PASSWORD=caluma
      - VISIBILITY_CLASSES=caluma.core.visibilities.Any
      - PERMISSION_CLASSES=caluma.core.permissions.AllowAny

volumes:
  dbdata:
