version: "3.4"

services:
  interval:
    build:
      args:
        - requirements=requirements-dev.txt
    environment:
      - CALUMA_URI=http://caluma:8000/graphql
    volumes:
      - ./:/app

  db:
    environment:
      - POSTGRES_PASSWORD=caluma
    ports:
      - "${DATABASE_PORT:-5432}:${DATABASE_PORT:-5432}"

  caluma:
    environment:
      - ENV=dev
