version: "3.4"

services:
  interval:
    build:
      context: .
    depends_on:
      - caluma

  db:
    image: postgres:9.6-alpine@sha256:a97ee77d345908ebb6e92298e4753833daae2b606339d7c03e91c369b9409078
    environment:
      - POSTGRES_USER=caluma
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -p ${DATABASE_PORT:-5432}

  caluma:
    image: projectcaluma/caluma:latest@sha256:3146c195656cbff4fec44dc443e230a823228fdbe609a9f29d2f4d151ddd9f92
    ports:
      - "8000:8000"
    depends_on:
      - db

    environment:
      - DATABASE_HOST=db
      - SECRET_KEY=uuuuuu
      - ALLOWED_HOSTS=*
      - DATABASE_PASSWORD=caluma
      - VISIBILITY_CLASSES=caluma.core.visibilities.Any
      - PERMISSION_CLASSES=caluma.core.permissions.AllowAny

volumes:
  dbdata:
