version: "3.4"

services:
  interval:
    build:
      context: .
    depends_on:
      - caluma

  db:
    image: postgres:9.6-alpine@sha256:bfb07024013642670bb36d533da2260a32ab11dc6ed8a873e7b2d1af319d1211
    environment:
      - POSTGRES_USER=caluma
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -p ${DATABASE_PORT:-5432}

  caluma:
    image: projectcaluma/caluma:latest@sha256:bddd0a73e3bbd15a96f0495c8a0f867b639f3261ccc69185451a14052c17245e
    ports:
      - "8000:8000"
    depends_on:
      - db

    environment:
      - DATABASE_HOST=db
      - SECRET_KEY=uuuuuu
      - ALLOWED_HOSTS=*
      - DATABASE_PASSWORD=caluma
      - VISIBILITY_CLASSES=caluma.core.visibilities.Any
      - PERMISSION_CLASSES=caluma.core.permissions.AllowAny

volumes:
  dbdata:
